### ISSUE TITLE
Participantes como Contribuidores

### ISSUE THREAD

**Issue by jlsilva01** [luigimilanez/Sistema-de-Conta-Digital#1]
Ola pessoal, onde estão os demais participantes do grupo cadastrados como contribuidores?
Nenhum cadastrado até este momento.

**Comment by luigimilanez** [comment]
Olá,
Já havia encaminhado o convite de colaborador para todos ainda na quinta feira. Vou pedir para o Roger aceitar o convite.

![fetchdemo](https://github.com/luigimilanez/Sistema-de-Conta-Digital/assets/89088603/7f981baa-ba68-4701-96ff-1604fbee44b7)
