### ISSUE TITLE
Alteração na tabela de Log

### ISSUE THREAD

**Issue by luigimilanez** [luigimilanez/Sistema-de-Conta-Digital#11]
Aglomerar todos os dados deletados em um <b>JSON</b> e inserir tal em <b>APENAS</b> uma coluna com datatype <b>VARCHAR(MAX)</b> ao invés de criar uma tabela com inúmeras colunas.

**Comment by jlsilva01** [comment]
Você pode usar este exemplo para gerar o _result set_ do SQL Server em formato JSON.

`DECLARE @antes varchar(max) = (select * from deleted for json auto)`

**Comment by luigimilanez** [comment]
Código ajustado! Será inserido no próximo commit

![fetchdemo](https://github.com/luigimilanez/Sistema-de-Conta-Digital/assets/89088603/d0a880ae-102e-4cc1-91f0-3371ac109b15)
