### ISSUE TITLE
Diagrama de Banco de Dados do projeto

### ISSUE THREAD

**Issue by luigimilanez** [luigimilanez/Sistema-de-Conta-Digital#2]
Boa noite, Jorge.
Pode dar uma averiguada no nosso diagrama?

![fetchdemo](https://github.com/luigimilanez/Sistema-de-Conta-Digital/assets/89088603/9eda2338-6c52-4d16-93a7-b2ee25452686)

**Comment by jlsilva01** [comment]
Sugeriria você trocar o tipo de dados money por numeric (14,2). 
Preferência por nome de tabelas no singular. 
Alguns campos pk/fk você usou id e alguns não. Busque um padrão e procure segui-lo em todo o projeto. 
Campo de ativo/inativo você pode deixar somente um campo bit. 1 para ativo e zero para inativo. 

De inicio creio que seja isso. Depois em aula verificaremos as relacionamentos das tabelas e possíveis normalizações.
