### ISSUE TITLE
Índices não clusterizados

### ISSUE THREAD

**Issue by luigimilanez** [luigimilanez/Sistema-de-Conta-Digital#4]
Boa tarde, Jorge.

Estava alimentando nossa planilha de dicionário de dados e ao analisar o código de criação do nosso banco de dados (gerado pelo site "app.sqldbm.com") percebi que foi atribuído um index não clusterizado para todas as chaves estrangeiras em todas as tabelas. Isso é uma boa prática? Podemos deixar assim?

[Link para o nosso código criador de tabelas](https://github.com/luigimilanez/Sistema-de-Conta-Digital/blob/main/createDatabase.sql)

**Comment by jlsilva01** [comment]
Não é muito comum isso.
Apesar de muitos autores defenderem isso, não é muito comum criar índex para todas as FKs do banco de dados. 
Só se cria índices que realmente forem utilizados. Índices não utilizados é recurso sendo desperdiçado no banco de dados. 
Se quiserem deixar isso e justificar, só procurem algum autor ou documento que valide isso e tá tudo ok.
