### ISSUE TITLE
Conferir o dicionário de dados

### ISSUE THREAD

**Issue by luigimilanez** [luigimilanez/Sistema-de-Conta-Digital#5]
Boa tarde, equipe!

Podem conferir o dicionário de dados para verificar se está tudo de acordo com o código de criação de tabelas?
[Link para o dicionário de dados](https://github.com/luigimilanez/Sistema-de-Conta-Digital/blob/main/Dicion%C3%A1rio/Dicionario_de_dados.xlsx)
[Link para o código de criação de tabelas](https://github.com/luigimilanez/Sistema-de-Conta-Digital/blob/main/Cria%C3%A7%C3%A3oDB/createDatabase.sql)

**Comment by miguelcimolin** [comment]
Olá, dei uma conferida no arquivo e aparentemente está OK. Lembrando que falta atualizar a nova tabela log_cliente_deletado.

**Comment by miguelcimolin** [comment]
O dicionário de dados foi conferido e atualizado.
