### ISSUE TITLE
Verificação do funcionamento do script de populamento de tabelas

### ISSUE THREAD

**Issue by luigimilanez** [luigimilanez/Sistema-de-Conta-Digital#6]
Boa tarde, equipe!

Alguém pode verificar se executando o código de criação de tabelas + o código das triggers + o código do populamento das tabelas irá gerar algum erro? Caso ocorrer algum erro, favor corrigir.

[Link para o arquivo de criação de tabelas](https://github.com/luigimilanez/Sistema-de-Conta-Digital/blob/main/Cria%C3%A7%C3%A3oDB/createDatabase.sql)
[Link para a pasta das triggers](https://github.com/luigimilanez/Sistema-de-Conta-Digital/tree/main/Objetos)
[Link para o arquivo de populamento de tabelas](https://github.com/luigimilanez/Sistema-de-Conta-Digital/blob/main/PopulaTabelas/populaTabela.sql)

**Comment by luigimilanez** [comment]
Obs: não pode popular as tabelas Emprestimodesativado e Faturadesativada

**Comment by miguelcimolin** [comment]
Opa, acabei de atualizar o script de população!
